### ISSUE TITLE
troubles with haxe-autocompletion

### ISSUE THREAD

**Issue by R3D9477** [massiveinteractive/mpartial#12]
Hi. I have little trouble: haxe-autocompletion don't work in PartialFragment.
This feature returns to me next error: "Compiler error. Error: No completion point was found".

In Partial it works fine.

Thanks.

**Comment by elsassph** [comment]
Unfortunately this project is neither supported nor recommended anymore.

**Comment by R3D9477** [comment]
Too bad! :( It was good project
