### ISSUE TITLE
cannot compile examples

### ISSUE THREAD

**Issue by postite** [massiveinteractive/mpartial#6]
i get ..
Method requires partial metadata. Cannot override example.Display.new

**Comment by postite** [comment]
ok my bad .. it goes well using github version ... 
btw this lib is awwwesome !

**Comment by misprintt** [comment]
Good to hear

It was on my list today but i didn't get a chance to respond.

Minor changes do end up on master between releases, but we try to tag every haxelib release so you can grab examples that match.
